coordinator=true
node-scheduler.include-coordinator=false
http-server.http.port=8080
# discovery-server.enabled=true
discovery.uri=http://trino:8080
# http-server.authentication.type=PASSWORD
http-server.authentication.allow-insecure-over-http=true
http-server.process-forwarded=true
internal-communication.shared-secret=ctm0WeCIrpSjeDriB3E+6erElcY1fTLMRkFArAxnSOhvHN/2KW4S5fY6tJa9t62lY3vAvSIP58v6AEfGyAXKMrT8NJjLHjVBQVnqLHBL60B19c9Sk3yljJE4pCClL0ktEdCT31EdzF/BHw/7mqV3Ie/9LN7xAcEJg8yQRHpP8/L5gQMvxkDSwHEweZ5a2aimAOeI5PetJhNrZsO3ELqpza18d5JnPeyX66m6Lb80Dt4DRRkzWcXaTt9mO1PQF7hR4SdTgJgm8FBSwOWwxoTLm5qCllHDSy+2zJMRjqpjz48Bsc2ACuQqMfowxU5DNtyxw+IWdMhwUrBICW8Qx3TPK7MuuBIbjYB/xtHi7K9pvw00Cn8Lo4Nne6MRbBM38wA27G0ekp6g19gKTXS6dyxj/y6ImUasN+iqzWZurIUOZ72sqFxFTrUQ/UldazFvk/7xNJK0vModzX4kfitlQth9a7l6gIc23WdxTI3Xtgd+M5L4ww0TgY0U3QHJDDMo/voWbAdoR8qBpY9EMAChLxnN6DMUV/W9lj6oDx8ydGPpt5ld6hrUAnDbEbUX1B/8HSPW97WgnmhSbC+VbvjQEQwrIYNUpchhQt3wvB1dPswZgeevVLKGY9gEcxSKwXQw08LINw7zdEIqtnBBgkPmvRoL71hJm2i5zss8xoPF4+vLMwI=
